### ISSUE TITLE
Packages on java

### ISSUE THREAD

**Issue by ghost** [UnAfraid/VotingReward#6]
They point to github. If you wish, I send a pull request morning or if you have time fix it.

**Comment by UnAfraid** [comment]
To fix what? :P 
Package name was intended to be named like that.

**Comment by Sacrifice78** [comment]
I refer to:
package com.github.unafraid.votingreward; import com.github.unafraid.votingreward.VotingSettings.MessageType;import com.github.unafraid.votingreward.interfaceprovider.api.IOnVoicedCommandHandler;import com.github.unafraid.votingreward.interfaceprovider.api.IPlayerInstance;
But if you like that... for me... its ok.

**Comment by ghost** [comment]
I refer to:
package com.github.unafraid.votingreward; import com.github.unafraid.votingreward.VotingSettings.MessageType;import com.github.unafraid.votingreward.interfaceprovider.api.IOnVoicedCommandHandler;import com.github.unafraid.votingreward.interfaceprovider.api.IPlayerInstance;
... on javas...
If you like so... "About tastes there is nothing written..." on this case yes, you're author... you put packages how you want. Only was an apreciation... but no error so. Wasn't my intention to criticize you. No more no less... I can't do it... ;)
This next days I will test it...

Thank you Mr. ;)
