### ISSUE TITLE
Script don't load... ¿...?

### ISSUE THREAD

**Issue by ghost** [UnAfraid/VotingReward#8]
![1231](https://cloud.githubusercontent.com/assets/13767243/10439074/dcfae648-7137-11e5-93db-121452da364f.jpg)
seems to be that imports cant be resolved...

**Comment by UnAfraid** [comment]
Make sure you've copied all 3 libs into into your server's libs directory!

You may wanna check my Wiki https://github.com/UnAfraid/VotingReward/wiki
https://github.com/UnAfraid/VotingReward/wiki/%5B2%5D-Integration-with-L2J-Server
