### ISSUE TITLE
HWID

### ISSUE THREAD

**Issue by lucario27** [UnAfraid/VotingReward#9]
Unafraid , can u help me whit HWID for votereward of topzone ? i have smartguard...

**Comment by UnAfraid** [comment]
For L2J check this one https://github.com/UnAfraid/VotingReward/blob/master/VotingRewardL2jInterface/src/main/java/com/github/unafraid/votingreward/l2j/L2JPlayer.java#L80

For L2P check this one https://github.com/UnAfraid/VotingReward/blob/master/VotingRewardL2ROInterface/src/main/java/com/github/unafraid/votingreward/l2ro/L2ROPlayer.java#L82

All you gotta do is return the hwid
